### ISSUE TITLE
This is NOT a multi platform library

### ISSUE THREAD

**Issue by CreativeRobotics** [Infineon/TLE5012-Magnetic-Angle-Sensor#20]
This library will not compile for most Arduino board distributions so it should NOT be labelled in the library properties file as:

> architectures=*

The library only appears to work with the AVR board distribution.

**Comment by jaenrig-ifx** [comment]
Updated -> https://github.com/Infineon/TLE5012-Magnetic-Angle-Sensor/releases/tag/v3.1.0
