### ISSUE TITLE
Update readouts always trigger an update

### ISSUE THREAD

**Issue by MorganSandercock** [Infineon/TLE5012-Magnetic-Angle-Sensor#4]
The functions which read out the "update" registers always trigger an update. This is not the correct usage of that trigger. The trigger should only be pulled once and then a group of registers can be read out with a consistent set of values instead of getting just the current reading from the register. 

An example use might be to trigger an update and then read out both speed and position at that instant. This sensor is so fast that reading a speed and then reading a position will get data from two different instants in time.

**Comment by OlafFilies** [comment]
triggerUpdate() fix is now included into release 2.0.1. Thanks for checking this.
